import type { BirthProfile, NatalChart, PlanetPlacement, RelationshipAstrology, ZodiacSign } from "../../types/astrology";

export const SAMPLE_BIRTH_PROFILE: BirthProfile = {
  id: "preview-astrology-map",
  name: "Sample profile",
  birthDate: "1994-05-08",
  birthTime: "10:15",
  birthPlace: "Preview City",
  latitude: 33.4484,
  longitude: -112.074,
  timezone: "America/Phoenix",
  timezoneOffset: -7,
  createdAt: "2026-01-01T00:00:00.000Z",
  updatedAt: "2026-01-01T00:00:00.000Z",
};

const SAMPLE_HOUSE_SIGNS: ZodiacSign[] = [
  "leo",
  "virgo",
  "libra",
  "scorpio",
  "sagittarius",
  "capricorn",
  "aquarius",
  "pisces",
  "aries",
  "taurus",
  "gemini",
  "cancer",
];

const SAMPLE_HOUSE_THEMES = [
  "identity",
  "resources",
  "voice",
  "home",
  "pleasure",
  "ritual",
  "partnership",
  "depth",
  "meaning",
  "direction",
  "community",
  "dream life",
];

const SAMPLE_PLACEMENTS: PlanetPlacement[] = [
  { body: "sun", sign: "taurus", degree: 18, house: 10, meaning: "You build self-trust through craft, consistency, and visible results." },
  { body: "moon", sign: "cancer", degree: 7, house: 12, meaning: "Your inner weather is private, protective, and deeply responsive to atmosphere." },
  { body: "rising", sign: "leo", degree: 14, house: 1, meaning: "You meet the world through warmth, presence, and a visible creative signal." },
  { body: "mercury", sign: "gemini", degree: 3, house: 11, meaning: "Your mind moves through pattern, language, and quick social intelligence." },
  { body: "venus", sign: "aries", degree: 22, house: 9, meaning: "Affection becomes honest when it has freedom, courage, and direct movement." },
  { body: "mars", sign: "leo", degree: 9, house: 1, meaning: "Your drive strengthens when the action has heart and a clear stage." },
  { body: "jupiter", sign: "taurus", degree: 2, house: 10, meaning: "Opportunity grows through patience, quality, and work that can be trusted." },
  { body: "saturn", sign: "capricorn", degree: 27, house: 6, meaning: "Discipline becomes useful when it is embodied in routine, service, and skill." },
  { body: "uranus", sign: "aquarius", degree: 16, house: 7, meaning: "Partnership needs room for independence, honesty, and future-facing choices." },
  { body: "neptune", sign: "pisces", degree: 11, house: 8, meaning: "Depth work asks for spiritual boundaries and careful emotional translation." },
  { body: "pluto", sign: "scorpio", degree: 19, house: 4, meaning: "Private transformation begins where family patterns and inner safety meet." },
];

export const SAMPLE_CHART: NatalChart = {
  id: "sample-astrology-map",
  provider: "mock",
  source: "sample",
  mode: "sample",
  calculatedAt: SAMPLE_BIRTH_PROFILE.updatedAt,
  birthProfile: SAMPLE_BIRTH_PROFILE,
  placements: SAMPLE_PLACEMENTS,
  aspects: [
    { from: "sun", to: "jupiter", type: "conjunction", orb: 3.2, strength: 88, meaning: "Steady confidence grows when values and opportunity point in the same direction." },
    { from: "moon", to: "neptune", type: "trine", orb: 4.5, strength: 74, meaning: "Emotional sensitivity becomes creative when it has a calm container." },
    { from: "venus", to: "mars", type: "trine", orb: 2.1, strength: 92, meaning: "Attraction and action cooperate when honesty stays warm." },
    { from: "mercury", to: "saturn", type: "square", orb: 5.0, strength: 63, meaning: "Ideas need structure before they become useful." },
    { from: "rising", to: "mars", type: "conjunction", orb: 5.0, strength: 78, meaning: "Presence and drive are linked; action is easier when it feels personally alive." },
  ],
  houses: SAMPLE_HOUSE_SIGNS.map((sign, index) => ({
    house: index + 1,
    sign,
    theme: SAMPLE_HOUSE_THEMES[index]!,
  })),
  sunSign: "taurus",
  moonSign: "cancer",
  risingSign: "leo",
  venusSign: "aries",
  marsSign: "leo",
  elementBalance: {
    fire: 4,
    earth: 3,
    air: 2,
    water: 4,
    dominant: "fire",
    meaning: "Fire leads because the Leo rising and Mars make presence, courage, and creative movement visible.",
  },
  modalityBalance: {
    cardinal: 4,
    fixed: 8,
    mutable: 2,
    dominant: "fixed",
    meaning: "Fixed signs anchor the chart, so consistency matters more than dramatic reinvention.",
  },
  validation: {
    partial: false,
    message: null,
    missing: [],
  },
  summary: {
    headline: "Taurus Sun · Cancer Moon · Leo Rising",
    short: "Taurus steadies the center, Cancer protects the inner world, and Leo shapes the first impression.",
    strengths: [
      "Creative presence becomes stronger when it is backed by patience.",
      "Emotional sensitivity works best with privacy and clear boundaries.",
      "The chart is fixed enough to build something lasting.",
    ],
    watch: [
      "Do not confuse steadiness with staying stuck.",
      "Let the Leo rising be warm without performing for approval.",
    ],
  },
};

export const SAMPLE_RELATIONSHIP: RelationshipAstrology = {
  id: "relationship-preview-astrology-map",
  provider: "mock",
  source: "preview",
  calculatedAt: SAMPLE_BIRTH_PROFILE.updatedAt,
  people: { user: SAMPLE_BIRTH_PROFILE },
  spaceBetween: "The Space Between You opens after another person consents to add their birth profile.",
  consentCopy: "Only add another person's birth details if they shared them with you.",
  highlights: [
    "Use signs as conversation prompts, not fixed judgments.",
    "Look for pacing, communication style, and emotional rhythm before making a story.",
    "No exact compatibility percentage is shown because relationships are not a scorecard.",
  ],
  invitations: [
    "Ask what feels easy between you.",
    "Ask what gets avoided when the connection feels intense.",
    "Notice whether silence creates safety or confusion.",
  ],
};

export const SAMPLE_TRANSITS = [
  {
    id: "sample-venus-square-saturn",
    title: "Venus square Saturn",
    transitPlanet: "Venus",
    natalPlanet: "Saturn",
    aspect: "square",
    orb: 1.2,
    area: ["Love", "Self-worth"],
    theme: ["boundaries", "distance", "commitment"],
    startDate: "2026-06-13",
    peakDate: "2026-06-13",
    endDate: "2026-06-13",
    action: "Tell the truth without asking for a reward.",
    why: "Venus themes touch Saturn pressure, so closeness may feel serious today.",
    evidence: ["Transit Venus square natal Saturn", "Orb: 1.2", "Peak: June 13, 2026"],
    strength: 96,
  },
  {
    id: "sample-moon-trine-venus",
    title: "Moon trine Venus",
    transitPlanet: "Moon",
    natalPlanet: "Venus",
    aspect: "trine",
    orb: 2.4,
    area: ["Love", "Mood"],
    theme: ["ease", "softness"],
    action: "Let the simple kind thing count.",
    why: "Moon and Venus support emotional warmth without forcing a big story.",
    evidence: ["Transit Moon trine natal Venus", "Orb: 2.4"],
    strength: 78,
  },
  {
    id: "sample-mercury-sextile-mars",
    title: "Mercury sextile Mars",
    transitPlanet: "Mercury",
    natalPlanet: "Mars",
    aspect: "sextile",
    orb: 3.1,
    area: ["Work", "Energy"],
    theme: ["clarity", "directness"],
    action: "Say the next step plainly.",
    why: "Mercury helps Mars turn pressure into a usable action.",
    evidence: ["Transit Mercury sextile natal Mars", "Orb: 3.1"],
    strength: 72,
  },
];
